# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'garrettD_Final_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for garrettD_Final_Project

  # add pods for desired Firebase products
  #https://firebase.google.com/docs/ios/setup#available-pods

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

end
